[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
ast = true

evm_version = "shanghai" # simulation may be false positive on bsc (PUSH0 opcode support)

optimizer=true
optimizer_runs=1000000

remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/=node_modules/@openzeppelin/contracts/"
]

fs_permissions = [
    { access = "read-write", path = "./"},
    { access = "none", path = ".env"} # TODO: check if it overrides previous rule
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
# Name "ethereum" breaks foundry configuration!
arbitrum = "${ARBITRUM_MAINNET_RPC_URL}"


[etherscan]
mainnet = { key = "${ETHEREUM_TOKEN}", chain = 1 }
arbitrum = { key = "${ARBITRUM_TOKEN}", chain = 42161 }
polygon = { key = "${POLYGON_TOKEN}", chain = 137 }
optimism = { key = "${OPTIMISM_TOKEN}", chain = 10 }
base = { key = "${BASE_TOKEN}", chain = 8453 }
bsc = { key = "${BSC_TOKEN}", chain = 56 }
avalanche = { key = "avascan", chain = 43114, url = "https://api.avascan.info/v2/network/mainnet/evm/43114/etherscan"}
mantle = { key = "verifyContract", chain = 5000, url = "https://api.routescan.io/v2/network/mainnet/evm/5000/etherscan"}
metis = { key = "verifyContract", chain = 1088, url = "https://api.routescan.io/v2/network/mainnet/evm/1088/etherscan" }
sei = { key = "verifyContract", chain = 1329, url = "https://seitrace.com/pacific-1/api" }
